### ISSUE TITLE
[Request] Reduce app size

### ISSUE THREAD

**Issue by alr86** [nain-F49FF806/sharepaste.oo#1]
The size of the application is too big compared to what it does (sending an api request), if you can reduce it a bit

**Comment by nain-F49FF806** [comment]
Thanks for opening the request. 

Currently, we have a single apk that contains both armv7 and armv8 build of the [`pbcli`](https://github.com/nain-F49FF806/pbcli) library. 
Those take approximately 5MiB and 7MiB respectively, totalling a minimum of 12MiB for the app. 

The rest is mostly compose UI and I do need to figure out where so much space is being used. 
Probably there's a way to selectively import UI components that we are using, which might reduce the size. 

Feel free to contribute a PR if you can find a way. 
I would like to have it reduced too, but a solution so far has eluded me. 


For now, if you want smaller *download* size, you can use the compressed version (.zip/.tar.xz) in [releases](https://github.com/nain-F49FF806/sharepaste.oo/releases).

**Comment by nain-F49FF806** [comment]
Update: Latest release [`2024.06.20`](https://github.com/nain-F49FF806/sharepaste.oo/releases/tag/2024.06.20) reduces size, by packaging separate apk for each supported platform  


**relevant commit**: https://github.com/nain-F49FF806/sharepaste.oo/commit/1c2dcb1319ebae3fa4e7c534255ab152936069be

**Comment by nain-F49FF806** [comment]
The above is already a significant improvement, for instance reducing uncompressed apk size by **40%** (for armabi-v7a devices). 

We could do more, by activating code shrinking and optimisation proguard rules. 
But the default behaviour for that is too aggressive and currently breaks the app. So I shall push it for later :tm: 

As such, I shall mark this _issue as completed_, since I've already had enough of messing with minify/resource shrinking. 
If you can figure out a `proguard-rules.pro` config that doesn't break the app, feel free to open a PR or new issue.
